/**
 * Grund token build.
 *
 * Reads the DTCG sources in tokens/ and emits the committed artefacts in src/:
 *   - tokens.css            CSS custom properties (--gds-*), light + dark
 *   - tokens.generated.ts   typed token object (the generated portion of tokens.ts)
 *   - tokens.allowlist.json  the overridable-semantic var names (per the theming contract)
 *
 * Light is the default (:root). Dark is delivered two ways: automatically via
 * `prefers-color-scheme`, and explicitly via `[data-color-scheme="dark"]`
 * (with `[data-color-scheme="light"]` to force light back).
 */
import StyleDictionary from "style-dictionary";
import { formattedVariables } from "style-dictionary/utils";
import { writeFileSync, mkdirSync } from "node:fs";

const PREFIX = "gds";
// Minimal transforms: kebab-case + prefix the names, pass values through as-is
// (values may be `TODO` placeholders, so no colour/dimension normalisation).
const TRANSFORMS = ["attribute/cti", "name/kebab"];

// Per-token maturity, two dimensions:
//   token: is the slot itself decided?  confirmed | draft
//   value: is the value defined?         set | candidate | placeholder | todo
// candidate = a real proposed value under active review; placeholder = a
// temporary stand-in not claimed as the answer. Explicit
// `$extensions["com.grund.status"]` wins; otherwise the token defaults to
// confirmed and the value is derived (a `TODO` value is todo, else set).
const VALUE_STATUSES = ["set", "candidate", "placeholder", "todo"];
const statusOf = (t) => {
  const ext = t.$extensions?.["com.grund.status"] ?? {};
  const token = ext.token === "draft" ? "draft" : "confirmed";
  const value = VALUE_STATUSES.includes(ext.value)
    ? ext.value
    : t.$value === "TODO"
      ? "todo"
      : "set";
  return { token, value };
};

// A token whose original value is a single reference (`{a.b.c}`) inherits the
// maturity of what it points at — so a component token wiring to a `candidate`
// semantic reads as `candidate`, not `set`. Returns the dotted ref path or null.
const refPathOf = (t) => {
  const ov = t.original?.$value;
  const m = typeof ov === "string" ? ov.match(/^\{([^}]+)\}$/) : null;
  return m ? m[1] : null;
};

const HEADER = `/**
 * GENERATED by Style Dictionary — do not edit by hand.
 * Source of truth: tokens/*.json. Regenerate with \`npm run build:tokens\`.
 */
`;

const LIGHT_SRC = [
  "tokens/primitives.json",
  "tokens/semantics.json",
  "tokens/components.json",
];
const DARK_SRC = [
  "tokens/primitives.json",
  "tokens/semantics.json",
  "tokens/semantics.dark.json",
  "tokens/components.json",
];

async function resolve(source) {
  const sd = new StyleDictionary({
    source,
    platforms: { css: { transforms: TRANSFORMS, prefix: PREFIX } },
    log: { verbosity: "silent" },
  });
  return sd.getPlatformTokens("css");
}

const cssVars = (dictionary, allTokens, outputReferences) =>
  formattedVariables({
    format: "css",
    dictionary: { ...dictionary, allTokens },
    outputReferences,
    usesDtcg: true,
  });

const light = await resolve(LIGHT_SRC);
const dark = await resolve(DARK_SRC);

// The tokens a dark theme overrides = those declared in semantics.dark.json.
const darkPaths = new Set(
  dark.allTokens
    .filter((t) => t.filePath.endsWith("semantics.dark.json"))
    .map((t) => t.path.join("."))
);
const inDark = (t) => darkPaths.has(t.path.join("."));

// outputReferences keeps the var() link (e.g. a color-mix wash stays tied to
// var(--gds-color-ink) instead of being flattened to a literal triplet) in the
// override blocks as well as :root.
const rootLines = cssVars(light, light.allTokens, true);
const darkLines = cssVars(dark, dark.allTokens.filter(inDark), true);
const lightLines = cssVars(light, light.allTokens.filter(inDark), true);

const css = `${HEADER}
:root {
${rootLines}
}

@media (prefers-color-scheme: dark) {
  :root {
${darkLines}
  }
}

[data-color-scheme="dark"] {
${darkLines}
}

[data-color-scheme="light"] {
${lightLines}
}
`;

// Nested token object (resolved values) for the TypeScript import surface.
function nest(allTokens) {
  const root = {};
  for (const t of allTokens) {
    let node = root;
    t.path.forEach((seg, i) => {
      if (i === t.path.length - 1) node[seg] = t.$value;
      else node = node[seg] ??= {};
    });
  }
  return root;
}

// Maturity status keyed by dot-path, so the gallery can label each token.
const status = {};
const refs = {}; // path → referenced path, for pure-reference tokens without explicit status
for (const t of light.allTokens) {
  const path = t.path.join(".");
  status[path] = statusOf(t);
  const ref = refPathOf(t);
  if (ref && !t.$extensions?.["com.grund.status"]) refs[path] = ref;
}
// Propagate referenced status into pure-reference tokens. Iterate to a fixpoint
// so chains (component → semantic → primitive) resolve regardless of order.
for (let i = 0; i < VALUE_STATUSES.length + 2; i++) {
  for (const [path, ref] of Object.entries(refs)) {
    if (status[ref]) status[path] = status[ref];
  }
}

const ts = `${HEADER}
export const generated = ${JSON.stringify(nest(light.allTokens), null, 2)} as const;

export const generatedStatus: Record<
  string,
  { token: "confirmed" | "draft"; value: "set" | "candidate" | "placeholder" | "todo" }
> = ${JSON.stringify(status, null, 2)};

export default generated;
`;

// The overridable surface = the semantic layer (per the theming contract).
const allowlist = light.allTokens
  .filter((t) => t.filePath.endsWith("semantics.json"))
  .map((t) => `--${t.name}`)
  .sort();

mkdirSync("src", { recursive: true });
writeFileSync("src/tokens.css", css);
writeFileSync("src/tokens.generated.ts", ts);
writeFileSync(
  "src/tokens.allowlist.json",
  JSON.stringify({ overridableSemantics: allowlist }, null, 2) + "\n"
);

console.log(
  `Built src/tokens.css, src/tokens.generated.ts, src/tokens.allowlist.json — ${light.allTokens.length} tokens, ${allowlist.length} overridable semantics.`
);
