/**
 * GENERATED by Style Dictionary — do not edit by hand.
 * Source of truth: tokens/*.json. Regenerate with `npm run build:tokens`.
 */

export const generated = {
  "color": {
    "brand": {
      "tobacco": "#E59500"
    },
    "popover": {
      "surface": "TODO",
      "border": "TODO",
      "text": "TODO",
      "text-muted": "TODO",
      "item-hover-bg": "TODO"
    },
    "focus-ring": "TODO"
  },
  "font": {
    "family": {
      "sans": "var(--font-geist-sans)"
    },
    "popover": {
      "size": "TODO",
      "weight": "TODO"
    }
  },
  "space": {
    "popover": {
      "padding": "TODO",
      "item-x": "TODO",
      "item-y": "TODO",
      "gap": "TODO"
    }
  },
  "radius": {
    "popover": "TODO",
    "popover-item": "TODO"
  },
  "shadow": {
    "popover": "TODO"
  },
  "popover": {
    "background": "TODO",
    "border-color": "TODO",
    "text-color": "TODO",
    "radius": "TODO",
    "padding": "TODO",
    "shadow": "TODO",
    "item": {
      "padding-x": "TODO",
      "padding-y": "TODO",
      "radius": "TODO",
      "hover-bg": "TODO"
    }
  }
} as const;

export const generatedStatus: Record<
  string,
  { token: "confirmed" | "draft"; value: "set" | "placeholder" | "todo" }
> = {
  "color.brand.tobacco": {
    "token": "confirmed",
    "value": "set"
  },
  "color.popover.surface": {
    "token": "confirmed",
    "value": "todo"
  },
  "color.popover.border": {
    "token": "confirmed",
    "value": "todo"
  },
  "color.popover.text": {
    "token": "confirmed",
    "value": "todo"
  },
  "color.popover.text-muted": {
    "token": "confirmed",
    "value": "todo"
  },
  "color.popover.item-hover-bg": {
    "token": "confirmed",
    "value": "todo"
  },
  "color.focus-ring": {
    "token": "confirmed",
    "value": "todo"
  },
  "font.family.sans": {
    "token": "confirmed",
    "value": "placeholder"
  },
  "font.popover.size": {
    "token": "confirmed",
    "value": "todo"
  },
  "font.popover.weight": {
    "token": "confirmed",
    "value": "todo"
  },
  "space.popover.padding": {
    "token": "confirmed",
    "value": "todo"
  },
  "space.popover.item-x": {
    "token": "confirmed",
    "value": "todo"
  },
  "space.popover.item-y": {
    "token": "confirmed",
    "value": "todo"
  },
  "space.popover.gap": {
    "token": "confirmed",
    "value": "todo"
  },
  "radius.popover": {
    "token": "confirmed",
    "value": "todo"
  },
  "radius.popover-item": {
    "token": "confirmed",
    "value": "todo"
  },
  "shadow.popover": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.background": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.border-color": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.text-color": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.radius": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.padding": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.shadow": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.item.padding-x": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.item.padding-y": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.item.radius": {
    "token": "confirmed",
    "value": "todo"
  },
  "popover.item.hover-bg": {
    "token": "confirmed",
    "value": "todo"
  }
};

export default generated;
